### ISSUE TITLE
[<MangaHub>] Connector not working

### ISSUE THREAD

**Issue by rwperrott** [manga-download/hakuneko#7945]
### Is there an existing issue for this connector?

- [x] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [x] I read it but nothing seems related

### Is the website of the connector working properly ?

- [x] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [x] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

https://api2.mangahub.io/graphql stopped working; nslookup fails to resolve api2.mangahub.io

It looks like https://api.mghcdn.com/graphql may have replaced it, give some view attempt with Developer Tools open for chapters on https://mangahub.io.

There doesn't appear to be any nightly build (build status link bad), so ticked just to allow submission.

### To Reproduce

1. Name of connector - MangaHub
3. Name of manga (if connector update is working) - NA
4. Name of chapter (if manga update is working) - NA
5. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
```txt
Connector.mjs:460 POST https://api2.mangahub.io/graphql net::ERR_NAME_NOT_RESOLVED
Connector.mjs:598 Error: Failed to fetch
    at MangaHub.fetchGraphQL (MangaHub.mjs:205) 
EventTarget {connector: MangaHub, id: "ware-ni-cheat-o-hazure-cheat-no-shoukan-yuusha-wa-isekai-de-yukkuri-kurashitai", title: "Ware ni Cheat o ~Hazure Cheat no Shoukan Yuusha wa Isekai de Yukkuri Kurashitai~", status: "completed", chapterCache: Array(0), …}
Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to fetch
    at MangaHub.fetchGraphQL (MangaHub.mjs:205)
```

**Comment by MikeZeDev** [comment]
Its cool to give the information about the change, its even cooler to follow the instructions and not checking boxes without reading.

![Image](https://github.com/user-attachments/assets/86bb56d0-b83a-4676-b810-7accf282eb45)

You didnt, as its fixed in nightly, 4 days ago.

https://github.com/manga-download/hakuneko/pull/7929

**Comment by 27136773** [comment]
> Its cool to give the information about the change, its even cooler to follow the instructions and not checking boxes without reading.
> 
> ![Image](https://github.com/user-attachments/assets/86bb56d0-b83a-4676-b810-7accf282eb45)
> 
> You didnt, as its fixed in nightly, 4 days ago.
> 
> [#7929](https://github.com/manga-download/hakuneko/pull/7929)

The description is contractional it says `Yes` and at the same time it says `didn't fix the issue`.
The opener reacted to the question `Perhaps your problem is already solved` by checking `Yes` but at the same time it says `No` 😉
